import json
import codecs

with codecs.open('src/context/LanguageContext.tsx', 'r', 'utf-8') as f:
    content = f.read()

# We will just rewrite the 	ranslations object inside the file.
new_translations = '''
const translations = {
  en: {
    "app.HowWasYourMovexTrip": "How was your Movex trip?",
    "app.RateYourJourneyExper": "Rate your journey experience",
    "app.SubmitFeedback": "Submit Feedback",
    "app.Status": "Status",
    "app.YouReOnline": "You're online",
    "app.WaitingForNewRideReq": "Waiting for new ride requests...",
    "app.WaitingForRides": "Waiting for rides...",
    "app.TodaySEarnings": "Today's Earnings",
    "app.OnlineHrs": "Online Hrs",
    "app.Distance": "Distance",
    "app.AllOffers": "All Offers",
    "app.ViewAll": "View all",
    "app.FridayFullOffer": "Friday Full Offer",
    "app.12Am12Am": "12am - 12am",
    "app.Incentive": "Incentive",
    "app.Order": "Order",
    "app.CompulsoryLogin": "Compulsory Login",
    "app.7Am10Am": "7am - 10am",
    "app.7Pm10Pm": "7pm - 10pm",
    "app.Ather": "Ather",
    "app.RentEv": "Rent EV",
    "app.EarnMore": "Earn More",
    "app.RideTheFuture": "Ride the Future",
    "app.141Day": "₹ 141/day",
    "app.KnowMore": "Know More",
    "app.GetDriverInsurance": "Get Driver Insurance",
    "app.ProtectYourselfAndYo": "Protect yourself and your family for just ₹199/yr.",
    "app.ApplyNow": "Apply Now",
    "app.CarMaintenanceOffer": "Car Maintenance Offer",
    "app.Flat20OffOnFullServi": "Flat 20% off on full service.",
    "app.ClaimOffer": "Claim Offer",
    "app.NewRideRequest": "New Ride Request",
    "app.PickupLocation": "Pickup Location",
    "app.DropLocation": "Drop Location",
    "app.EstEarnings": "Est. Earnings",
    "app.Decline": "Decline",
    "app.Accept": "Accept",
    "app.HeadingToPickup": "Heading to Pickup",
    "app.MapNavigation": "Map Navigation",
    "app.Call": "Call",
    "app.Chat": "Chat",
    "app.Cancel": "Cancel",
    "app.ArrivedAtLocation": "Arrived at Location",
    "app.Destination": "Destination",
    "app.CompleteTrip": "Complete Trip",
    "app.VerifyStartTrip": "Verify & Start Trip",
    "app.EG500": "e.g. 500",
    "app.LeaveCommentsOptiona": "Leave comments (optional)...",
    "app.EnterCustomerVerific": "Enter Customer Verification OTP",
    "home.goodMorning": "Good Morning",
    "home.goodAfternoon": "Good Afternoon",
    "home.goodEvening": "Good Evening",
    "home.whereTo": "Where to?",
    "home.searchDest": "Search destination...",
    "home.topupWallet": "Top-up Wallet",
    "home.recentPlaces": "Recent Places",
    "home.tabHome": "Home",
    "home.tabServices": "Services",
    "home.tabTrips": "Trips",
    "home.tabAccount": "Account",
    "home.tabWallet": "Wallet",
    "driverHome.youreOffline": "You're Offline",
    "driverHome.goOnline": "Go Online",
    "driverHome.totalEarnings": "Total Earnings",
    "driverHome.trips": "Trips",
    "driverHome.hoursOnline": "Hours Online",
    "app.ConfirmPickupLocation": "Confirm Pickup Location",
    "app.ConfirmDropLocation": "Confirm Drop Location",
    "app.Book": "Book",
    "app.Profile": "Profile",
    "app.EditProfile": "Edit Profile",
    "app.Language": "Language",
    "app.Logout": "Logout",
    "app.RideHistory": "Ride History",
    "app.Wallet": "Wallet"
  },
  ta: {
    "app.HowWasYourMovexTrip": "உங்கள் மூவெக்ஸ் பயணம் எப்படி இருந்தது?",
    "app.RateYourJourneyExper": "உங்கள் பயண அனுபவத்தை மதிப்பிடுங்கள்",
    "app.SubmitFeedback": "கருத்துக்களை சமர்ப்பி",
    "app.Status": "நிலை",
    "app.YouReOnline": "நீங்கள் ஆன்லைனில் உள்ளீர்கள்",
    "app.WaitingForNewRideReq": "புதிய சவாரி கோரிக்கைகளுக்காக காத்திருக்கிறது...",
    "app.WaitingForRides": "சவாரிகளுக்காக காத்திருக்கிறது...",
    "app.TodaySEarnings": "இன்றைய வருமானம்",
    "app.OnlineHrs": "ஆன்லைன் நேரம்",
    "app.Distance": "தூரம்",
    "app.AllOffers": "அனைத்து சலுகைகள்",
    "app.ViewAll": "அனைத்தையும் பார்",
    "app.FridayFullOffer": "வெள்ளிக்கிழமை முழு சலுகை",
    "app.12Am12Am": "12am - 12am",
    "app.Incentive": "ஊக்கத்தொகை",
    "app.Order": "ஆர்டர்",
    "app.CompulsoryLogin": "கட்டாய உள்நுழைவு",
    "app.7Am10Am": "7am - 10am",
    "app.7Pm10Pm": "7pm - 10pm",
    "app.Ather": "ஏதர்",
    "app.RentEv": "ஈவி வாடகைக்கு",
    "app.EarnMore": "மேலும் சம்பாதிக்க",
    "app.RideTheFuture": "எதிர்கால சவாரி",
    "app.141Day": "₹ 141/நாள்",
    "app.KnowMore": "மேலும் அறிய",
    "app.GetDriverInsurance": "ஓட்டுநர் காப்பீடு பெறுங்கள்",
    "app.ProtectYourselfAndYo": "ஆண்டுக்கு ₹199 மட்டும் செலுத்தி உங்களையும் உங்கள் குடும்பத்தையும் பாதுகாக்கவும்.",
    "app.ApplyNow": "இப்போதே விண்ணப்பிக்கவும்",
    "app.CarMaintenanceOffer": "கார் பராமரிப்பு சலுகை",
    "app.Flat20OffOnFullServi": "முழு சேவைக்கு 20% தள்ளுபடி.",
    "app.ClaimOffer": "சலுகையை பெறுங்கள்",
    "app.NewRideRequest": "புதிய சவாரி கோரிக்கை",
    "app.PickupLocation": "பிக்அப் இடம்",
    "app.DropLocation": "இறங்கும் இடம்",
    "app.EstEarnings": "மதிப்பிடப்பட்ட வருமானம்",
    "app.Decline": "நிராகரி",
    "app.Accept": "ஏற்றுக்கொள்",
    "app.HeadingToPickup": "பிக்அப் இடத்திற்கு செல்கிறது",
    "app.MapNavigation": "வரைபட வழிகாட்டி",
    "app.Call": "அழை",
    "app.Chat": "அரட்டை",
    "app.Cancel": "ரத்துசெய்",
    "app.ArrivedAtLocation": "இடத்தை அடைந்துவிட்டீர்கள்",
    "app.Destination": "செல்லுமிடம்",
    "app.CompleteTrip": "பயணத்தை முடி",
    "app.VerifyStartTrip": "சரிபார்த்து பயணத்தை தொடங்கு",
    "app.EG500": "உ.ம். 500",
    "app.LeaveCommentsOptiona": "கருத்துகளை இடவும் (விருப்பத்தேர்வு)...",
    "app.EnterCustomerVerific": "வாடிக்கையாளர் சரிபார்ப்பு OTP ஐ உள்ளிடவும்",
    "home.goodMorning": "காலை வணக்கம்",
    "home.goodAfternoon": "மதிய வணக்கம்",
    "home.goodEvening": "மாலை வணக்கம்",
    "home.whereTo": "எங்கே செல்ல வேண்டும்?",
    "home.searchDest": "சேருமிடத்தைத் தேடு...",
    "home.topupWallet": "வாலட்டை நிரப்பு",
    "home.recentPlaces": "சமீபத்திய இடங்கள்",
    "home.tabHome": "முகப்பு",
    "home.tabServices": "சேவைகள்",
    "home.tabTrips": "பயணங்கள்",
    "home.tabAccount": "கணக்கு",
    "home.tabWallet": "வாலட்",
    "driverHome.youreOffline": "நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்",
    "driverHome.goOnline": "ஆன்லைனுக்குச் செல்",
    "driverHome.totalEarnings": "மொத்த வருமானம்",
    "driverHome.trips": "பயணங்கள்",
    "driverHome.hoursOnline": "ஆன்லைன் நேரம்",
    "app.ConfirmPickupLocation": "பிக்அப் இடத்தை உறுதிப்படுத்து",
    "app.ConfirmDropLocation": "இறங்கும் இடத்தை உறுதிப்படுத்து",
    "app.Book": "முன்பதிவு செய்",
    "app.Profile": "சுயவிவரம்",
    "app.EditProfile": "சுயவிவரத்தைத் திருத்து",
    "app.Language": "மொழி",
    "app.Logout": "வெளியேறு",
    "app.RideHistory": "பயண வரலாறு",
    "app.Wallet": "வாலட்"
  }
};
'''

import re
content = re.sub(r'const translations = \{.*?\n\};', new_translations, content, flags=re.DOTALL)

with codecs.open('src/context/LanguageContext.tsx', 'w', 'utf-8') as f:
    f.write(content)

print('Success')
