import React, { createContext, useState, useContext, useEffect } from 'react';
import * as SecureStore from 'expo-secure-store';

type LanguageContextType = {
  language: 'en' | 'ta';
  setLanguage: (lang: 'en' | 'ta') => void;
  t: (key: string) => string;
};


const translations = {
  en: {
    "app.HowWasYourMovexTrip": "How was your Movex trip?",
    "app.RateYourJourneyExper": "Rate your journey experience",
    "app.SubmitFeedback": "Submit Feedback",
    "app.Status": "Status",
    "app.YouReOnline": "You're online",
    "app.WaitingForNewRideReq": "Waiting for new ride requests...",
    "app.WaitingForRides": "Waiting for rides...",
    "app.TodaySEarnings": "Today's Earnings",
    "app.OnlineHrs": "Online Hrs",
    "app.Distance": "Distance",
    "app.AllOffers": "All Offers",
    "app.ViewAll": "View all",
    "app.FridayFullOffer": "Friday Full Offer",
    "app.12Am12Am": "12am - 12am",
    "app.Incentive": "Incentive",
    "app.Order": "Order",
    "app.CompulsoryLogin": "Compulsory Login",
    "app.7Am10Am": "7am - 10am",
    "app.7Pm10Pm": "7pm - 10pm",
    "app.Ather": "Ather",
    "app.RentEv": "Rent EV",
    "app.EarnMore": "Earn More",
    "app.RideTheFuture": "Ride the Future",
    "app.141Day": "₹ 141/day",
    "app.KnowMore": "Know More",
    "app.GetDriverInsurance": "Get Driver Insurance",
    "app.ProtectYourselfAndYo": "Protect yourself and your family for just ₹199/yr.",
    "app.ApplyNow": "Apply Now",
    "app.CarMaintenanceOffer": "Car Maintenance Offer",
    "app.Flat20OffOnFullServi": "Flat 20% off on full service.",
    "app.ClaimOffer": "Claim Offer",
    "app.NewRideRequest": "New Ride Request",
    "app.PickupLocation": "Pickup Location",
    "app.DropLocation": "Drop Location",
    "app.EstEarnings": "Est. Earnings",
    "app.Decline": "Decline",
    "app.Accept": "Accept",
    "app.HeadingToPickup": "Heading to Pickup",
    "app.MapNavigation": "Map Navigation",
    "app.Call": "Call",
    "app.Chat": "Chat",
    "app.Cancel": "Cancel",
    "app.ArrivedAtLocation": "Arrived at Location",
    "app.Destination": "Destination",
    "app.CompleteTrip": "Complete Trip",
    "app.VerifyStartTrip": "Verify & Start Trip",
    "app.EG500": "e.g. 500",
    "app.LeaveCommentsOptiona": "Leave comments (optional)...",
    "app.EnterCustomerVerific": "Enter Customer Verification OTP",
    "home.goodMorning": "Good Morning",
    "home.goodAfternoon": "Good Afternoon",
    "home.goodEvening": "Good Evening",
    "home.whereTo": "Where to?",
    "home.searchDest": "Search destination...",
    "home.topupWallet": "Top-up Wallet",
    "home.recentPlaces": "Recent Places",
    "home.tabHome": "Home",
    "home.tabServices": "Services",
    "home.tabTrips": "Trips",
    "home.tabAccount": "Account",
    "home.tabWallet": "Wallet",
    "home.planRoute": "Plan Your Route",
    "home.searchPickup": "Search pickup location...",
    "home.setPickup": "Set Pickup Location",
    "home.searchDrop": "Search drop location...",
    "home.confirmDrop": "Confirm Drop Location",
    "home.whereDoYouWantToGo": "Where do you want to go?",
    "home.serviceCab": "Cab",
    "home.serviceBike": "Bike",
    "home.serviceAuto": "Auto",
    "home.serviceTour": "Tour",
    "home.serviceRental": "Rental",
    "home.serviceIntercity": "Intercity",
    "home.limitedOffer": "LIMITED OFFER",
    "home.firstRideFree": "FIRST RIDE FREE",
    "home.offerNewUsers": "Offer detected for new users.",
    "home.tapToApply": "Tap here to apply",
    "home.tapSearchBar": "Tap the search bar above",
    "home.enterDestination": "and enter your destination",
    "home.yourCityYourRide": "Your city, your ride.",
    "driverHome.youreOffline": "You're Offline",
    "driverHome.goOnline": "Go Online",
    "driverHome.totalEarnings": "Total Earnings",
    "driverHome.trips": "Trips",
    "driverHome.hoursOnline": "Hours Online",
    "app.ConfirmPickupLocation": "Confirm Pickup Location",
    "app.ConfirmDropLocation": "Confirm Drop Location",
    "app.Book": "Book",
    "app.Profile": "Profile",
    "app.EditProfile": "Edit Profile",
    "app.Language": "Language",
    "app.Logout": "Logout",
    "app.RideHistory": "Ride History",
    "app.Wallet": "Wallet",
    "profile.darkTheme": "Dark Theme",
    "profile.appLanguage": "App Language",
    "profile.alertSound": "Alert Sound",
    "profile.helpCentre": "Help Centre",
    "profile.supportTickets": "Support Tickets",
    "profile.settings": "Settings",
    "profile.referralTitle": "Referral & Earn",
    "profile.referralSub": "Invite your friends and earn rewards",
    "profile.logout": "Logout",
    "notifications.title": "Notifications",
    "notifications.all": "All",
    "notifications.unread": "Unread",
    "notifications.clearAll": "Clear all",
    "notifications.offerTitle": "Monday Full Day Offer",
    "notifications.offerSub": "Earn upto ₹7,00 Incentive",
    "notifications.timeAgo": "2mins ago",
    "wallet.availableBalance": "Available Balance",
    "wallet.withdraw": "Withdraw",
    "wallet.addMoney": "Add Money",
    "wallet.addMoneyTitle": "Add Money to Wallet",
    "wallet.addMoneySub": "Enter the amount you want to add",
    "wallet.selectPaymentMethod": "Select Payment Method",
    "wallet.cancel": "Cancel",
    "wallet.withdrawTitle": "Withdraw from Wallet",
    "wallet.available": "Available:",
    "wallet.max": "Max:",
    "support.title": "Support Tickets",
    "support.noTickets": "No tickets found"
  },
  ta: {
    "app.HowWasYourMovexTrip": "உங்கள் மூவெக்ஸ் பயணம் எப்படி இருந்தது?",
    "app.RateYourJourneyExper": "உங்கள் பயண அனுபவத்தை மதிப்பிடுங்கள்",
    "app.SubmitFeedback": "கருத்துக்களை சமர்ப்பி",
    "app.Status": "நிலை",
    "app.YouReOnline": "நீங்கள் ஆன்லைனில் உள்ளீர்கள்",
    "app.WaitingForNewRideReq": "புதிய சவாரி கோரிக்கைகளுக்காக காத்திருக்கிறது...",
    "app.WaitingForRides": "சவாரிகளுக்காக காத்திருக்கிறது...",
    "app.TodaySEarnings": "இன்றைய வருமானம்",
    "app.OnlineHrs": "ஆன்லைன் நேரம்",
    "app.Distance": "தூரம்",
    "app.AllOffers": "அனைத்து சலுகைகள்",
    "app.ViewAll": "அனைத்தையும் பார்",
    "app.FridayFullOffer": "வெள்ளிக்கிழமை முழு சலுகை",
    "app.12Am12Am": "12am - 12am",
    "app.Incentive": "ஊக்கத்தொகை",
    "app.Order": "ஆர்டர்",
    "app.CompulsoryLogin": "கட்டாய உள்நுழைவு",
    "app.7Am10Am": "7am - 10am",
    "app.7Pm10Pm": "7pm - 10pm",
    "app.Ather": "ஏதர்",
    "app.RentEv": "ஈவி வாடகைக்கு",
    "app.EarnMore": "மேலும் சம்பாதிக்க",
    "app.RideTheFuture": "எதிர்கால சவாரி",
    "app.141Day": "₹ 141/நாள்",
    "app.KnowMore": "மேலும் அறிய",
    "app.GetDriverInsurance": "ஓட்டுநர் காப்பீடு பெறுங்கள்",
    "app.ProtectYourselfAndYo": "ஆண்டுக்கு ₹199 மட்டும் செலுத்தி உங்களையும் உங்கள் குடும்பத்தையும் பாதுகாக்கவும்.",
    "app.ApplyNow": "இப்போதே விண்ணப்பிக்கவும்",
    "app.CarMaintenanceOffer": "கார் பராமரிப்பு சலுகை",
    "app.Flat20OffOnFullServi": "முழு சேவைக்கு 20% தள்ளுபடி.",
    "app.ClaimOffer": "சலுகையை பெறுங்கள்",
    "app.NewRideRequest": "புதிய சவாரி கோரிக்கை",
    "app.PickupLocation": "பிக்அப் இடம்",
    "app.DropLocation": "இறங்கும் இடம்",
    "app.EstEarnings": "மதிப்பிடப்பட்ட வருமானம்",
    "app.Decline": "நிராகரி",
    "app.Accept": "ஏற்றுக்கொள்",
    "app.HeadingToPickup": "பிக்அப் இடத்திற்கு செல்கிறது",
    "app.MapNavigation": "வரைபட வழிகாட்டி",
    "app.Call": "அழை",
    "app.Chat": "அரட்டை",
    "app.Cancel": "ரத்துசெய்",
    "app.ArrivedAtLocation": "இடத்தை அடைந்துவிட்டீர்கள்",
    "app.Destination": "செல்லுமிடம்",
    "app.CompleteTrip": "பயணத்தை முடி",
    "app.VerifyStartTrip": "சரிபார்த்து பயணத்தை தொடங்கு",
    "app.EG500": "உ.ம். 500",
    "app.LeaveCommentsOptiona": "கருத்துகளை இடவும் (விருப்பத்தேர்வு)...",
    "app.EnterCustomerVerific": "வாடிக்கையாளர் சரிபார்ப்பு OTP ஐ உள்ளிடவும்",
    "home.goodMorning": "காலை வணக்கம்",
    "home.goodAfternoon": "மதிய வணக்கம்",
    "home.goodEvening": "மாலை வணக்கம்",
    "home.whereTo": "எங்கே செல்ல வேண்டும்?",
    "home.searchDest": "சேருமிடத்தைத் தேடு...",
    "home.topupWallet": "வாலட்டை நிரப்பு",
    "home.recentPlaces": "சமீபத்திய இடங்கள்",
    "home.tabHome": "முகப்பு",
    "home.tabServices": "சேவைகள்",
    "home.tabTrips": "பயணங்கள்",
    "home.tabAccount": "கணக்கு",
    "home.tabWallet": "வாலட்",
    "home.planRoute": "உங்கள் வழியை திட்டமிடுங்கள்",
    "home.searchPickup": "பிக்அப் இடத்தைத் தேடு...",
    "home.setPickup": "பிக்அப் அமை",
    "home.searchDrop": "இறங்கும் இடத்தை தேடு...",
    "home.confirmDrop": "இறங்கும் இடத்தை உறுதிப்படுத்துக",
    "home.whereDoYouWantToGo": "நீங்கள் எங்கு செல்ல விரும்புகிறீர்கள்?",
    "home.serviceCab": "கார்",
    "home.serviceBike": "பைக்",
    "home.serviceAuto": "ஆட்டோ",
    "home.serviceTour": "சுற்றுலா",
    "home.serviceRental": "வாடகை",
    "home.serviceIntercity": "வெளியூர்",
    "home.limitedOffer": "வரையறுக்கப்பட்ட சலுகை",
    "home.firstRideFree": "முதல் பயணம் இலவசம்",
    "home.offerNewUsers": "புதிய பயனர்களுக்கான சலுகை.",
    "home.tapToApply": "பயன்படுத்த இங்கே தட்டவும்",
    "home.tapSearchBar": "மேலே உள்ள தேடல் பட்டியை தட்டவும்",
    "home.enterDestination": "உங்கள் சேருமிடத்தை உள்ளிடவும்",
    "home.yourCityYourRide": "உங்கள் நகரம், உங்கள் பயணம்.",
    "driverHome.youreOffline": "நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்",
    "driverHome.goOnline": "ஆன்லைனுக்குச் செல்",
    "driverHome.totalEarnings": "மொத்த வருவாய்",
    "driverHome.trips": "பயணங்கள்",
    "driverHome.hoursOnline": "ஆன்லைன் நேரம்",
    "app.ConfirmPickupLocation": "பிக்அப் இடத்தை உறுதிப்படுத்துக",
    "app.ConfirmDropLocation": "டிராப் இடத்தை உறுதிப்படுத்துக",
    "app.Book": "புக் செய்",
    "app.Profile": "சுயவிவரம்",
    "app.EditProfile": "சுயவிவரத்தை திருத்துக",
    "app.Language": "மொழி",
    "app.Logout": "வெளியேறு",
    "app.RideHistory": "பயண வரலாறு",
    "app.Wallet": "வாலெட்",
    "profile.darkTheme": "டார்க் தீம்",
    "profile.appLanguage": "பயன்பாட்டு மொழி",
    "profile.alertSound": "அலர்ட் சத்தம்",
    "profile.helpCentre": "உதவி மையம்",
    "profile.supportTickets": "ஆதரவு டிக்கெட்டுகள்",
    "profile.settings": "அமைப்புகள்",
    "profile.referralTitle": "பரிந்துரை செய்து சம்பாதிக்கவும்",
    "profile.referralSub": "உங்கள் நண்பர்களை அழைத்து பரிசுகளை பெறுங்கள்",
    "profile.logout": "வெளியேறு",
    "notifications.title": "அறிவிப்புகள்",
    "notifications.all": "அனைத்தும்",
    "notifications.unread": "படிக்காதவை",
    "notifications.clearAll": "அனைத்தையும் அழி",
    "notifications.offerTitle": "திங்கட்கிழமை முழு நேர சலுகை",
    "notifications.offerSub": "₹7,00 வரை ஊக்கத்தொகை பெறுங்கள்",
    "notifications.timeAgo": "2 நிமிடங்களுக்கு முன்",
    "wallet.availableBalance": "இருப்பு தொகை",
    "wallet.withdraw": "திரும்பப் பெறு",
    "wallet.addMoney": "பணம் சேர்",
    "wallet.addMoneyTitle": "வாலெட்டில் பணம் சேர்க்கவும்",
    "wallet.addMoneySub": "நீங்கள் சேர்க்க விரும்பும் தொகையை உள்ளிடவும்",
    "wallet.selectPaymentMethod": "பணம் செலுத்தும் முறையைத் தேர்ந்தெடுக்கவும்",
    "wallet.cancel": "ரத்துசெய்",
    "wallet.withdrawTitle": "வாலெட்டிலிருந்து திரும்பப் பெறவும்",
    "wallet.available": "இருப்பு:",
    "wallet.max": "அதிகபட்சம்:",
    "support.title": "ஆதரவு டிக்கெட்டுகள்",
    "support.noTickets": "டிக்கெட்டுகள் எதுவும் கிடைக்கவில்லை"
  }
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<'en' | 'ta'>('en');

  useEffect(() => {
    SecureStore.getItemAsync('app_lang').then(lang => {
      if (lang === 'ta') setLanguageState('ta');
    });
  }, []);

  const setLanguage = (lang: 'en' | 'ta') => {
    setLanguageState(lang);
    SecureStore.setItemAsync('app_lang', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
